replicaCount: 1

env: dev

image:
  repository: us-central1-docker.pkg.dev/project-1cdbea51-6334-4e02-967/app-images/paymentservice
  tag: "v0.1.20"
  pullPolicy: IfNotPresent

terminationGracePeriodSeconds: 5

annotations:
  instrumentation.opentelemetry.io/inject-nodejs: "app-instrumentation"
  resource.opentelemetry.io/service.name: "paymentservice"

containers:
  - name: server
    ports:
      - containerPort: 50051
        name: grpc
    env:
      - name: PORT
        value: "50051"
      - name: DISABLE_PROFILER
        value: "1"
      - name: OTEL_SERVICE_NAME
        value: "paymentservice"

    readinessProbe:
      initialDelaySeconds: 5
      periodSeconds: 10
      grpc:
        port: 50051

    livenessProbe:
      initialDelaySeconds: 5
      periodSeconds: 10
      grpc:
        port: 50051

    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi

service:
  enabled: true
  type: ClusterIP
  name: grpc
  port: 50051
  targetPort: 50051

serviceAccount:
  create: true
  name: "paymentservice"

podDisruptionBudget:
  enabled: false
  minAvailable: 1