apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: boutique-services-prod
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - env: prod
          - list:
              elements:
                - service: frontend
                  chart: charts/microservices/frontend
                - service: cartservice
                  chart: charts/microservices/cartservice
                - service: currencyservice
                  chart: charts/microservices/currencyservice
                - service: productcatalogservice
                  chart: charts/microservices/productcatalogservice
                - service: adservice
                  chart: charts/microservices/adservice
                - service: checkoutservice
                  chart: charts/microservices/checkoutservice
                - service: emailservice
                  chart: charts/microservices/emailservice
                - service: loadgenerator
                  chart: charts/microservices/loadgenerator
                - service: paymentservice
                  chart: charts/microservices/paymentservice
                - service: recommendationservice
                  chart: charts/microservices/recommendationservice
                - service: shippingservice
                  chart: charts/microservices/shippingservice
  template:
    metadata:
      name: "{{service}}-{{env}}"
    spec:
      project: boutique-platform
      source:
        repoURL: https://github.com/tanya-domi/terraform-helm-gitops-fullStackObservability.git
        targetRevision: main
        path: "{{chart}}"
        helm:
          releaseName: "{{service}}"
          valueFiles:
            - ../../../gitops/envs/{{env}}/globals.yaml
            - ../../gitops/envs/{{env}}/values-{{service}}.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{env}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
