apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-image-digest
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: check-image-digest
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - dev
                - stage
                - prod
      validate:
        message: "Images must use digest pinning (image@sha256:...)."
        pattern:
          spec:
            containers:
              - image: "*@sha256:*"
