deploymentName: currencyservice-deployment
serviceName: currencyservice

appLabel: currencyservice
appName: currencyservice
jobLabel: currencyservice

replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/project-1cdbea51-6334-4e02-967/app-images/currencyservice
  tag: "v0.1.20"
  pullPolicy: IfNotPresent 

annotations:
  instrumentation.opentelemetry.io/inject-nodejs: "app-instrumentation"

containers:
  - name: server
    ports:
      - containerPort: 7000
    env:
      - name: PORT
        value: "7000"
      - name: DISABLE_PROFILER
        value: "1"
      - name: OTEL_SERVICE_NAME
        value: currencyservice

    readinessProbe:
      grpc:
        port: 7000
    livenessProbe:
      grpc:
        port: 7000
    # resources:
    #   requests:
    #     cpu: 100m
    #     memory: 64Mi
    #   limits:
    #     cpu: 200m
    #     memory: 128Mi

    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi

service:
  enabled: true
  type: ClusterIP
  name: grpc
  port: 7000
  targetPort: 7000

serviceAccount:
  create: true
  name: "currencyservice"

profiler_enabled: "false"
