apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: external-secrets
  annotations:
    iam.gke.io/gcp-service-account: "eso-gcp-sa@project-1cdbea51-6334-4e02-967.iam.gserviceaccount.com"
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store
spec:
  provider:
    gcpsm:
      projectID: "project-1cdbea51-6334-4e02-967"
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets

# cluster level infrastructure
# Step 1: Install ESO via Helm with Service Account Overrides

# helm repo add external-secrets https://charts.external-secrets.
# helm repo update
# helm search repo external-secrets --versions
# EXTERNALSECRETS_VERSION=v2.7.0 


# helm install external-secrets external-secrets/external-secrets \
#     -n external-secrets \
#     --create-namespace \
#     --version $EXTERNALSECRETS_VERSION \
#     --set installCRDs=true \
#     --set serviceAccount.create=true \
#     --set serviceAccount.name="external-secrets-sa"

# verify ESO installation
# kubectl get pods -n external-secrets
# kubectl get crds | grep external-secrets

# Check for SecretSynced status 
# kubectl get externalsecret otel-redis-secret-bridge -n monitoring

# This should display the generated secret
# kubectl get secret prod-redis-endpoint -n monitoring