apiVersion: v1
kind: ServiceAccount
metadata:
  name: thanos-sa
  namespace: monitoring   
  annotations:
    iam.gke.io/gcp-service-account: "thanos-gcp-sa@project-1cdbea51-6334-4e02-967.iam.gserviceaccount.com"