global:
  gateway:
    enabled: true
    name: boutique-gateway
    className: gke-l7-gylb
    host: staging.tanyadominicsheytech.eu
    certificates:
      - boutique-staging-ssl-cert

  route:
    enabled: true
    name: frontend-route
    gatewayName: boutique-gateway
    host: staging.tanyadominicsheytech.eu
    serviceName: frontend
    servicePort: 80

  configMapName: online-boutique-staging-configmap
  
  redis:
    address: "redis-service.boutique.svc.cluster.local:6379" #"10.34.0.4:6379" Dev Memorystore IP

  replicaCount: 2

  gcp:
    serviceAccountEmail: "github-actions-pusher@project-1cdbea51-6334-4e02-967.iam.gserviceaccount.com"

  features:
    enableTracing: "true"
    enable_profiler: "false"
      
  # Add overrides values
releaseInfo:
  enabled: true

frontend:
  podDisruptionBudget:
    enabled: true
    minAvailable: 1

checkoutservice:
  podDisruptionBudget:
    enabled: true
    minAvailable: 1

shippingservice:
  podDisruptionBudget:
    enabled: true
    minAvailable: 1

