replicaCount: 1

env: dev


image:
  repository: us-central1-docker.pkg.dev/project-1cdbea51-6334-4e02-967/app-images/adservice
  tag: "v0.1.19"
  pullPolicy: IfNotPresent

terminationGracePeriodSeconds: 5

annotations:
  instrumentation.opentelemetry.io/inject-java: "app-instrumentation"
  resource.opentelemetry.io/service.name: "adservice"

containers:
  - name: server
    ports:
      - containerPort: 9555
        name: grpc
    env:
      - name: PORT
        value: "9555"
      - name: OTEL_SERVICE_NAME
        value: "adservice"
      - name: OTEL_LOGS_EXPORTER
        value: "otlp"
      - name: OTEL_LOG_LEVEL
        value: "info"
      - name: OTEL_JAVAAGENT_LOGGING
        value: "application"
      - name: OTEL_INSTRUMENTATION_LOG4J_APPENDER_ENABLED
        value: "true"

    readinessProbe:
      initialDelaySeconds: 60
      periodSeconds: 15
      grpc:
        port: 9555

    livenessProbe:
      initialDelaySeconds: 60
      periodSeconds: 15
      grpc:
        port: 9555

    resources:
      requests:
        cpu: 100m
        memory: 180Mi
      limits:
        cpu: 300m
        memory: 300Mi

service:
  enabled: true
  type: ClusterIP
  name: grpc
  port: 9555
  targetPort: 9555

serviceAccount:
  create: true
  name: "adservice"

podDisruptionBudget:
  enabled: false
  minAvailable: 1