---
global:
  activeProfile: default
  services:
    productcatalogservice: "productcatalogservice:3550"
    currencyservice: "currencyservice:7000"
    cartservice: "cartservice:7070"
    recommendationservice: "recommendationservice:8080"
    shippingservice: "shippingservice:50051"
    checkoutservice: "checkoutservice:5050"
    adservice: "adservice:9555"
  
  ingress:
    enabled: true
    className: gce
    name: boutique
    serviceName: frontend
    servicePort: 80
    annotations:
      kubernetes.io/ingress.class: "gce"
      networking.gke.io/v1beta1.FrontendConfig: "boutique-frontend-config"
      

releaseInfo:
  enabled: false

frontend:
  podDisruptionBudget:
    enabled: false
    minAvailable: 1

checkoutservice:
  podDisruptionBudget:
    enabled: false
    minAvailable: 1



