---
global:
  activeProfile: default
  services:
    productcatalogservice: "productcatalogservice:3550"
    currencyservice: "currencyservice:7000"
    cartservice: "cartservice:7070"
    recommendationservice: "recommendationservice:8080"
    shippingservice: "shippingservice:50051"
    checkoutservice: "checkoutservice:5050"
    adservice: "adservice:9555"


  gateway:
    enabled: false
    name: boutique-gateway
    className: gke-l7-gylb
    host: ""
    certificates:
      - boutique-dev-ssl-cert

  route:
    enabled: false
    name: frontend-route
    gatewayName: boutique-gateway
    host: ""
    serviceName: frontend
    servicePort: 80
      

releaseInfo:
  enabled: false

frontend:
  podDisruptionBudget:
    enabled: false
    minAvailable: 1

checkoutservice:
  podDisruptionBudget:
    enabled: false
    minAvailable: 1



