deploymentName: cartservice-deployment

env:
  cartservice: true
  redis: false

serviceName: cartservice

appLabel: cartservice
appName: cartservice
jobLabel: cartservice

replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/project-1cdbea51-6334-4e02-967/app-images/cartservice
  tag: "v0.1.20"
  pullPolicy: IfNotPresent
  # imagePullSecrets:
  #   - name: my-registry-key

terminationGracePeriodSeconds: 5

annotations:
  instrumentation.opentelemetry.io/inject-dotnet: "true"

containers:
  - name: server
    ports:
      - containerPort: 7070
    env:
      - name: OTEL_SERVICE_NAME
        value: "cartservice"
      # Inject the live value directly from the ESO-managed secret resource.
      - name: REDIS_ADDR
        valueFrom:
          secretKeyRef:
            name: prod-redis-endpoint
            key: redis-endpoint

    readinessProbe:
      initialDelaySeconds: 20
      grpc:
        port: 7070

    livenessProbe:
      initialDelaySeconds: 25
      periodSeconds: 15
      grpc:
        port: 7070

    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi

service:
  enabled: true
  type: ClusterIP
  name: grpc
  port: 7070
  targetPort: 7070

serviceAccount:
  create: true
  name: cartservice
