apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: boutique-frontend-config
  namespace: boutique
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
