name: CI adservice

permissions:
  contents: write
  id-token: write
  pull-requests: write

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "apps/adservice/**"
      - "charts/microservices/adservice/**"
      - ".github/workflows/reusable-service-ci.yaml"
      - ".github/workflows/ci-adservice.yml"


jobs:
  ci:
    uses: ./.github/workflows/reusable-service-ci.yaml
    with:
      service: adservice
    secrets: inherit
