name: CI currencyservice

permissions:
  contents: write
  id-token: write
  pull-requests: write

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "apps/currencyservice/**"
      - "charts/microservices/currencyservice/**"
      - ".github/workflows/reusable-service-ci.yaml"
      - ".github/workflows/ci-currencyservice.yml"


jobs:
  ci:
    uses: ./.github/workflows/reusable-service-ci.yaml
    with:
      service: currencyservice
    secrets: inherit
