name: CI cartservice

permissions:
  contents: write
  id-token: write
  pull-requests: write

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "apps/cartservice/**"
      - "charts/microservices/cartservice/**"
      - ".github/workflows/reusable-service-ci.yml"
      - ".github/workflows/ci-cartservice.yml"

jobs:
  ci:
    uses: ./.github/workflows/reusable-service-ci.yml
    with:
      service: cartservice
    secrets: inherit
