name: CI emailservice

permissions:
  contents: write
  id-token: write
  pull-requests: write

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "apps/emailservice/**"
      - "charts/microservices/emailservice/**"
      - ".github/workflows/reusable-service-ci.yaml"
      - ".github/workflows/ci-emailservice.yml"

  pull_request:
    branches: [main]
    paths:
      - "apps/emailservice/**"
      - "charts/microservices/emailservice/**"

jobs:
  ci:
    uses: ./.github/workflows/reusable-service-ci.yaml
    with:
      service: emailservice
    secrets: inherit
