name: CI checkoutservice

permissions:
  contents: write
  id-token: write
  pull-requests: write

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "apps/checkoutservice/**"
      - "charts/microservices/checkoutservice/**"
      - ".github/workflows/reusable-service-ci.yaml"
      - ".github/workflows/ci-checkoutservice.yml"

jobs:
  ci:
    uses: ./.github/workflows/reusable-service-ci.yaml
    with:
      service: emailservice
    secrets: inherit
