name: CI frontend

permissions:
  contents: write
  id-token: write
  pull-requests: write

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "apps/frontend/**"
      - "charts/microservices/frontend/**"
      - ".github/workflows/reusable-service-ci.yaml"
      - ".github/workflows/ci-frontend.yml"

  pull_request:
    branches: [main]
    paths:
      - "apps/frontend/**"
      - "charts/microservices/frontend/**"

jobs:
  ci:
    uses: ./.github/workflows/reusable-service-ci.yaml
    with:
      service: frontend
    secrets: inherit