name: CI paymentservice

permissions:
  contents: write
  id-token: write
  pull-requests: write

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "apps/paymentservice/**"
      - "charts/microservices/paymentservice/**"
      - ".github/workflows/reusable-service-ci.yaml"
      - ".github/workflows/ci-paymentservice.yml"

  pull_request:
    branches: [main]
    paths:
      - "apps/paymentservice/**"
      - "charts/microservices/paymentservice/**"

jobs:
  ci:
    uses: ./.github/workflows/reusable-service-ci.yaml
    with:
      service: paymentservice
    secrets: inherit
