name: CI recommendationservice

permissions:
  contents: write
  id-token: write
  pull-requests: write

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "apps/recommendationservice/**"
      - "charts/microservices/recommendationservice/**"
      - ".github/workflows/reusable-service-ci.yaml"
      - ".github/workflows/ci-recommendationservice.yml"


jobs:
  ci:
    uses: ./.github/workflows/reusable-service-ci.yaml
    with:
      service: recommendationservice
    secrets: inherit
