name: CI shippingservice

permissions:
  contents: write
  id-token: write
  pull-requests: write

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "apps/shippingservice/**"
      - "charts/microservices/shippingservice/**"
      - ".github/workflows/reusable-service-ci.yaml"
      - ".github/workflows/ci-shippingservice.yml"

jobs:
  ci:
    uses: ./.github/workflows/reusable-service-ci.yaml
    with:
      service: shippingservice
    secrets: inherit
